### PR TITLE
pdbx-mmcif.md

### PR DESCRIPTION
**Pull request by jdwestbrook**
This file describes the metadata framework used for archiving
macromolecular structure data by the Protein Data Bank.

### CODE REVIEW

**Comment by alex-ball** [comment]
Thanks for your submission. Before we merge it in, please could you look at the following issues:

 1. 'subjects' uses a controlled vocabulary and should be one or more of
      - arts-and-humanities
      - engineering
      - general
      - life-sciences
      - physical-sciences-and-mathematics
      - social-and-behavioral-sciences

 2. 'disciplines' uses a controlled vocabulary. For the terms currently in use, look at `_data/disciplines.yaml`. Please use the encoded version that comes after `/resources/metadata-standards/disciplinary/` in that file, e.g. metabolic-biochemistry. If needed, new terms can be derived from the more granular terms in [HESA JACS3](https://www.hesa.ac.uk/component/content/article?id=1787).

 3. The link `http://mmcif.wwpdb.org/` looks like it should be under `website` rather than `specification_url`.

 4. You have a typo: `Crystallogarphic`

 5. Under `mappings` and `sponsors` please use full URLs, i.e. including the initial http://, otherwise they will not work when transformed to HTML.

 6. Under `version` you do not need to specify "Current Version", this is assumed.

 7. Under description you have a typo: "depositon". Would it be possible to have a little more on mmCIF and what the standard is used for?

**Comment by alex-ball** [comment]
Please could you also change the `name` value to `pdbx-mmcif` to match the file name.

**Comment by jdwestbrook** [comment]
Please let me know if further changes are required.

**Comment by alex-ball** [comment]
Thanks for making those changes, much appreciated. Just a few more:

 1. Just today I found that the behaviour of the engine that generates the site has changed, so we have had to change the top level `name` field (where you have `pdbx-mmcif`) to be called `slug` instead. Sorry about that.

 2. The discipline names also have to be in 'slug' format, e.g. physics, structural-chemistry. Perhaps more obscurely, we have abbreviated 'Molecular biology, biophysics & biochemistry' to the slug 'molecular-biology'.

 3. Could you add a little more to the description, explaining about mmCIF and what the standard is used for? Also, it looks like the 'depositon' typo is still there.

**Pull request merged**
